name: Build, Scan, & Update Image

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECS_SERVICE: gatus-service
  ECS_CLUSTER: gatus-cluster

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c
        with: 
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ secrets.OIDC_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd

      - name: Build Docker Image
        id: build-image
        run: |
            echo "Building Docker Image"
            cd ./app
            docker build -t ${{ secrets.ECR_REPO }}:${{ github.sha }} .
            echo "image=${{ secrets.ECR_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Grype Container Scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
        with:
          image: ${{ secrets.ECR_REPO }}:${{ github.sha }}
          severity-cutoff: medium
          fail-build: false # In an actual production environment, this would be set to 'true', to fail the pipeline after detecting a security issue
          output-format: table
          
      - name: Push Docker Image to ECR
        id: image-push
        run: |
            echo "Pushing Docker image to ECR"
            docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}
            echo "Push successful"
        
      - name: Render New Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@138c24f321fdbdf7edee4a685519d253cae2cdea
        with:
            task-definition-family: ${{ secrets.FAMILY_TD }}
            container-name: ${{ secrets.CONTAINER_NAME }}
            image: ${{ steps.build-image.outputs.image }}
    
      - name: Deploy New Task Definition
        id: deploy-td
        uses: aws-actions/amazon-ecs-deploy-task-definition@c465972ecbd160473f22e683363b422a5412a3de
        with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: ${{ env.ECS_SERVICE }}
            cluster: ${{ env.ECS_CLUSTER }}