name: Build and Push Docker Image to ECR

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECS_SERVICE: gatus-service
  ECS_CLUSTER: gatus-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Switch Directory
        run: |
          cd ./app
          ls

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with: 
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ secrets.OIDC_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.1.6

      - name: Build Docker Image
        id: build-image
        run: |
            echo "Building Docker Image"
            cd ./app
            docker build -t ${{ secrets.ECR_REPO }}:${{ github.sha }} .
            echo "image=${{ secrets.ECR_REPO }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Grype Container Scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
        with:
          image: ${{ secrets.ECR_REPO }}:${{ github.sha }}
          severity-cutoff: high
          fail-build: false # In an actual production environment, this would be set to 'true', to fail build
          
      - name: Push Docker Image to ECR
        id: image-push
        run: |
            echo "Pushing Docker image to ECR"
            docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}
            echo "Push successful"
        
      - name: Render New Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.9.0
        with:
            task-definition-family: ${{ secrets.FAMILY_TD }}
            container-name: ${{ secrets.CONTAINER_NAME }}
            image: ${{ steps.build-image.outputs.image }}
    
      - name: Deploy New Task Definition
        id: deploy-td
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.6.3
        with:
            task-definition: ${{ steps.task-def.outputs.task-definition }}
            service: ${{ env.ECS_SERVICE }}
            cluster: ${{ env.ECS_CLUSTER }}