name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.15.3

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c
        with: 
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ secrets.OIDC_REGION }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform-version: $TF_VERSION
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: IaC Scanning
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        with:
          output_format: cli
          soft_fail: true # in production environments, this would be set to false, to fail the pipeline 

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    
    needs: terraform-plan
    if: success()
    steps:
      - name: Terraform Apply
        run: terraform apply --auto-approve